# Generated by Django 5.0.4 on 2024-04-13 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(to="songs.artist"),
        ),
        migrations.AddField(
            model_name="artist",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="most_recently_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                default="3fHIPcwahABoxrB2vZ1kFE",
                on_delete=django.db.models.deletion.CASCADE,
                to="songs.album",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(to="songs.artist"),
        ),
    ]
